#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_CODE_DIR="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

prompt() {
  local variable="$1" label="$2" default_value="$3" value
  read -r -p "${label} [${default_value}]: " value
  printf -v "${variable}" '%s' "${value:-${default_value}}"
}

prompt_secret() {
  local variable="$1" label="$2" current_value="${!1:-}" value
  if [[ -n "${current_value}" ]]; then
    read -r -s -p "${label} [Enter keeps current value]: " value
  else
    read -r -s -p "${label}: " value
  fi
  echo
  printf -v "${variable}" '%s' "${value:-${current_value}}"
}

ensure_secret() {
  local variable="$1" label="$2"
  if [[ -n "${!variable:-}" ]]; then
    echo "Using saved or exported ${label}."
  else
    prompt_secret "${variable}" "${label}"
  fi
}

load_credentials() {
  local credentials_file="$1" owner mode
  [[ -f "${credentials_file}" ]] || return 0
  owner="$(stat -c '%u' "${credentials_file}")"
  mode="$(stat -c '%a' "${credentials_file}")"
  if [[ "${owner}" != "$(id -u)" || "${mode}" != "600" ]]; then
    echo "Refusing to load ${credentials_file}: it must be owned by the current user with mode 600." >&2
    exit 2
  fi

  local env_hf="${HF_TOKEN:-}" env_wandb="${WANDB_API_KEY:-}"
  local env_serverchan="${SERVERCHAN_SENDKEY:-}" env_vast="${VAST_API_KEY:-}"
  # This file is created by save_credentials below and is accepted only after owner/mode validation.
  # shellcheck disable=SC1090
  source "${credentials_file}"
  [[ -n "${env_hf}" ]] && HF_TOKEN="${env_hf}"
  [[ -n "${env_wandb}" ]] && WANDB_API_KEY="${env_wandb}"
  [[ -n "${env_serverchan}" ]] && SERVERCHAN_SENDKEY="${env_serverchan}"
  [[ -n "${env_vast}" ]] && VAST_API_KEY="${env_vast}"
  echo "Loaded saved credentials from ${credentials_file}"
}

save_credentials() {
  local credentials_file="$1" credentials_dir temporary_file
  credentials_dir="$(dirname -- "${credentials_file}")"
  mkdir -p "${credentials_dir}"
  chmod 700 "${credentials_dir}"
  temporary_file="$(mktemp "${credentials_dir}/credentials.env.XXXXXX")"
  chmod 600 "${temporary_file}"
  {
    echo "# Generated by interactive_kuavo_train.sh. Keep this file outside the Git working tree."
    printf 'export HF_TOKEN=%q\n' "${CREDENTIAL_HF_TOKEN:-}"
    printf 'export WANDB_API_KEY=%q\n' "${CREDENTIAL_WANDB_API_KEY:-}"
    printf 'export SERVERCHAN_SENDKEY=%q\n' "${CREDENTIAL_SERVERCHAN_SENDKEY:-}"
    printf 'export VAST_API_KEY=%q\n' "${CREDENTIAL_VAST_API_KEY:-}"
  } >"${temporary_file}"
  mv -f "${temporary_file}" "${credentials_file}"
  chmod 600 "${credentials_file}"
  echo "Saved credentials to ${credentials_file} (mode 600)"
}

yes_no() {
  local variable="$1" label="$2" default_value="$3" value suffix
  if [[ "${default_value}" == "1" ]]; then suffix="Y/n"; else suffix="y/N"; fi
  while true; do
    read -r -p "${label} [${suffix}]: " value
    value="${value:-$([[ "${default_value}" == "1" ]] && echo y || echo n)}"
    case "${value,,}" in
      y|yes) printf -v "${variable}" '%s' 1; return ;;
      n|no) printf -v "${variable}" '%s' 0; return ;;
      *) echo "Please answer y or n." >&2 ;;
    esac
  done
}

echo "Kuavo Pi0.5 JAX interactive Vast launcher"
echo "Secrets stay in this process environment and are not written into the repository."
echo

while true; do
  read -r -p "Task: 1) right arm / 345 episodes  2) dual arm / 264 episodes [1]: " task_choice
  task_choice="${task_choice:-1}"
  case "${task_choice}" in
    1)
      ROBOT_TASK="task1"
      DATASET_REPO="larryi/kuavo-task1-345"
      task_slug="kuavo-task1-345"
      break
      ;;
    2)
      ROBOT_TASK="task2"
      DATASET_REPO="larryi/kuavo-task2-264"
      task_slug="kuavo-task2-264"
      break
      ;;
    *) echo "Choose 1 or 2." >&2 ;;
  esac
done

while true; do
  read -r -p "Mode: 1) mandatory 10-step smoke  2) full training [1]: " mode_choice
  mode_choice="${mode_choice:-1}"
  case "${mode_choice}" in
    1) PIPELINE_MODE="smoke"; CONFIRM_FULL_TRAIN="NO"; mode_slug="smoke"; break ;;
    2) PIPELINE_MODE="train"; CONFIRM_FULL_TRAIN="YES"; mode_slug="full"; break ;;
    *) echo "Choose 1 or 2." >&2 ;;
  esac
done

while true; do
  read -r -p "GPU profile: 1) RTX PRO 6000 96GB x1  2) A100 80GB x4  3) custom [1]: " gpu_choice
  gpu_choice="${gpu_choice:-1}"
  case "${gpu_choice}" in
    1)
      GPU_IDS="0"; GPU_COUNT="1"; FSDP_DEVICES="1"
      REQUIRE_GPU_NAME="RTX PRO 6000"; MIN_GPU_MEMORY_MB="90000"; MIN_GPU_FREE_MB="88000"
      CUDA_NVCC_VERSION="auto"; EMA_DECAY="None"; REMAT_POLICY="dots_with_no_batch_dims_saveable"
      default_batch="$([[ "${PIPELINE_MODE}" == "smoke" ]] && echo 1 || echo 16)"
      gpu_slug="rtxpro6000"
      break
      ;;
    2)
      GPU_IDS="0,1,2,3"; GPU_COUNT="4"; FSDP_DEVICES="4"
      REQUIRE_GPU_NAME="A100"; MIN_GPU_MEMORY_MB="79000"; MIN_GPU_FREE_MB="70000"
      CUDA_NVCC_VERSION="auto"; EMA_DECAY="0.99"; REMAT_POLICY="nothing_saveable"
      default_batch="$([[ "${PIPELINE_MODE}" == "smoke" ]] && echo 4 || echo 32)"
      gpu_slug="a100x4"
      break
      ;;
    3)
      prompt GPU_IDS "CUDA_VISIBLE_DEVICES list" "0"
      prompt GPU_COUNT "GPU count" "1"
      prompt FSDP_DEVICES "FSDP devices" "${GPU_COUNT}"
      prompt REQUIRE_GPU_NAME "Required GPU name substring" "A100"
      prompt MIN_GPU_MEMORY_MB "Minimum total memory MiB" "79000"
      prompt MIN_GPU_FREE_MB "Minimum free memory MiB" "70000"
      prompt CUDA_NVCC_VERSION "nvidia-cuda-nvcc-cu12 version (auto uses uv.lock)" "auto"
      prompt EMA_DECAY "EMA decay (None disables it)" "None"
      prompt REMAT_POLICY "Remat policy" "nothing_saveable"
      default_batch="${GPU_COUNT}"
      gpu_slug="gpu${GPU_COUNT}"
      break
      ;;
    *) echo "Choose 1, 2, or 3." >&2 ;;
  esac
done

prompt GLOBAL_BATCH_SIZE "Global batch size" "${default_batch}"
if (( GLOBAL_BATCH_SIZE % GPU_COUNT != 0 )); then
  echo "Global batch size must be divisible by GPU count." >&2
  exit 2
fi

prompt NUM_TRAIN_STEPS "Full-training optimizer steps" "30000"
prompt SAVE_INTERVAL "Checkpoint interval" "1000"
prompt KEEP_PERIOD "Checkpoint preservation period" "1000000000"
LR_TAIL_START_STEP=""
LR_TAIL_DECAY_STEPS=""
LR_TAIL_DECAY_LR=""
yes_no LR_TAIL_ENABLED "Enable a continuous cosine LR tail for resumed training?" 0
if [[ "${LR_TAIL_ENABLED}" == "1" ]]; then
  prompt LR_TAIL_START_STEP "Tail start global step" "44000"
  prompt LR_TAIL_DECAY_STEPS "Tail duration in steps" "6000"
  prompt LR_TAIL_DECAY_LR "Tail final learning rate" "2.5e-7"
fi
prompt NUM_WORKERS "Data-loader workers" "8"
prompt WORK_ROOT "Persistent work root" "/workspace/kuavo_pi05"
prompt CODE_DIR "OpenPI checkout" "${DEFAULT_CODE_DIR}"
prompt BASE_PARAMS "Pi0.5 JAX base params" "gs://openpi-assets/checkpoints/pi05_base/params"
prompt UV_DEFAULT_INDEX "PyPI index" "https://pypi.org/simple"
# The frozen dependency graph requires Python 3.11. Vast images often export PYTHON_VERSION=3.12,
# so the interactive launcher must not inherit that ambient value.
PYTHON_VERSION="3.11"

CREDENTIALS_FILE="${OPENPI_VAST_CREDENTIALS_FILE:-${WORK_ROOT}/.secrets/credentials.env}"
load_credentials "${CREDENTIALS_FILE}"
CREDENTIAL_HF_TOKEN="${HF_TOKEN:-}"
CREDENTIAL_WANDB_API_KEY="${WANDB_API_KEY:-}"
CREDENTIAL_SERVERCHAN_SENDKEY="${SERVERCHAN_SENDKEY:-}"
CREDENTIAL_VAST_API_KEY="${VAST_API_KEY:-}"

timestamp="$(date +%Y%m%d_%H%M%S)"
default_run_id="${task_slug}_${gpu_slug}_${mode_slug}_${timestamp}"
prompt RUN_ID "Run ID" "${default_run_id}"
prompt MODEL_REPO "HF model repo (owner/name)" "larryi/${RUN_ID}"

MODEL_REPO_PRIVATE=0
yes_no MODEL_REPO_PRIVATE "Keep the output model repository private? Public is the recommended Kuavo default" 0
if [[ "${MODEL_REPO_PRIVATE}" == "0" ]]; then
  echo "WARNING: all uploaded checkpoint tensors, logs, and manifests in ${MODEL_REPO} will be publicly downloadable."
fi

ensure_secret HF_TOKEN "HF token"
[[ -n "${HF_TOKEN}" ]] || { echo "HF token is required." >&2; exit 2; }
CREDENTIAL_HF_TOKEN="${HF_TOKEN}"

yes_no WANDB_ENABLED "Enable Weights & Biases?" "$([[ -n "${WANDB_API_KEY:-}" ]] && echo 1 || echo 0)"
if [[ "${WANDB_ENABLED}" == "1" ]]; then
  ensure_secret WANDB_API_KEY "W&B API key"
  CREDENTIAL_WANDB_API_KEY="${WANDB_API_KEY}"
  prompt WANDB_PROJECT "W&B project" "openpi-kuavo"
else
  WANDB_API_KEY=""
  WANDB_PROJECT="openpi-kuavo"
fi

yes_no SERVERCHAN_ENABLED "Send a final ServerChan notification?" "$([[ -n "${SERVERCHAN_SENDKEY:-}" ]] && echo 1 || echo 0)"
if [[ "${SERVERCHAN_ENABLED}" == "1" ]]; then
  ensure_secret SERVERCHAN_SENDKEY "ServerChan SendKey"
  CREDENTIAL_SERVERCHAN_SENDKEY="${SERVERCHAN_SENDKEY}"
else
  SERVERCHAN_SENDKEY=""
fi

AUTO_UPLOAD=1
yes_no AUTO_STOP_INSTANCE "Stop the Vast instance after completion?" 1
AUTO_STOP_ON_FAILURE=0
AUTO_STOP_ON_UPLOAD_FAILURE=0
VAST_INSTANCE_ID="${VAST_INSTANCE_ID:-}"
VAST_API_KEY="${VAST_API_KEY:-}"
if [[ "${AUTO_STOP_INSTANCE}" == "1" ]]; then
  prompt VAST_INSTANCE_ID "Vast instance ID" "${VAST_INSTANCE_ID:-required}"
  [[ "${VAST_INSTANCE_ID}" != "required" ]] || { echo "Vast instance ID is required." >&2; exit 2; }
  ensure_secret VAST_API_KEY "Vast API key"
  [[ -n "${VAST_API_KEY}" ]] || { echo "Vast API key is required." >&2; exit 2; }
  CREDENTIAL_VAST_API_KEY="${VAST_API_KEY}"
  yes_no AUTO_STOP_ON_UPLOAD_FAILURE "Stop even if HF upload fails (prevents unattended billing)?" 1
  yes_no AUTO_STOP_ON_FAILURE "Stop after an ordinary training/setup failure too?" 0
fi

yes_no SAVE_CREDENTIALS "Save/update credentials in ${CREDENTIALS_FILE}?" 1
if [[ "${SAVE_CREDENTIALS}" == "1" ]]; then
  save_credentials "${CREDENTIALS_FILE}"
fi

RESUME=0
yes_no RESUME "Resume this exact RUN_ID/model repository?" 0
OVERWRITE=0

echo
echo "Launch summary"
printf '  task/dataset:       %s / %s\n' "${ROBOT_TASK}" "${DATASET_REPO}"
printf '  mode/steps:         %s / %s\n' "${PIPELINE_MODE}" "$([[ "${PIPELINE_MODE}" == "smoke" ]] && echo 10 || echo "${NUM_TRAIN_STEPS}")"
if [[ "${LR_TAIL_ENABLED}" == "1" ]]; then
  printf '  LR tail:            step %s + %s steps -> %s\n' \
    "${LR_TAIL_START_STEP}" "${LR_TAIL_DECAY_STEPS}" "${LR_TAIL_DECAY_LR}"
fi
printf '  checkpoint keep:    period %s\n' "${KEEP_PERIOD}"
printf '  Python/PyPI:        %s / %s\n' "${PYTHON_VERSION}" "${UV_DEFAULT_INDEX}"
printf '  GPUs/FSDP/batch:    %s / %s / %s\n' "${GPU_IDS}" "${FSDP_DEVICES}" "${GLOBAL_BATCH_SIZE}"
printf '  run:                %s\n' "${RUN_ID}"
printf '  model repo:         %s (%s)\n' "${MODEL_REPO}" "$([[ "${MODEL_REPO_PRIVATE}" == "1" ]] && echo private || echo PUBLIC)"
printf '  auto upload/stop:   yes / %s\n' "$([[ "${AUTO_STOP_INSTANCE}" == "1" ]] && echo yes || echo no)"
printf '  stop upload failure:%s\n' "$([[ "${AUTO_STOP_ON_UPLOAD_FAILURE}" == "1" ]] && echo yes || echo no)"
echo
read -r -p "Type START to launch: " confirmation
[[ "${confirmation}" == "START" ]] || { echo "Cancelled."; exit 1; }

export ROBOT_TASK DATASET_REPO PIPELINE_MODE CONFIRM_FULL_TRAIN
export GPU_IDS GPU_COUNT FSDP_DEVICES GLOBAL_BATCH_SIZE REQUIRE_GPU_NAME MIN_GPU_MEMORY_MB MIN_GPU_FREE_MB
export CUDA_NVCC_VERSION EMA_DECAY REMAT_POLICY NUM_TRAIN_STEPS SAVE_INTERVAL KEEP_PERIOD NUM_WORKERS
export LR_TAIL_START_STEP LR_TAIL_DECAY_STEPS LR_TAIL_DECAY_LR
export WORK_ROOT CODE_DIR BASE_PARAMS UV_DEFAULT_INDEX PYTHON_VERSION RUN_ID MODEL_REPO MODEL_REPO_PRIVATE HF_TOKEN
export WANDB_API_KEY WANDB_PROJECT SERVERCHAN_SENDKEY AUTO_UPLOAD AUTO_STOP_INSTANCE
export AUTO_STOP_ON_FAILURE AUTO_STOP_ON_UPLOAD_FAILURE VAST_INSTANCE_ID VAST_API_KEY RESUME OVERWRITE

exec "${CODE_DIR}/scripts/vast/run_pi05_pipeline.sh"
